<?php


namespace App\Tests\Unit;


use App\Entity\Admin;
use App\Entity\Customers;
use PHPUnit\Framework\TestCase;

class EffectiveTest extends testCase{

    /**
     * @var Customers
     */
    private Customers $Effectif;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->Effectif = new Customers();
        
    }
    public function  testGetRS():void
    {
        $value = 'test RAISON_SOCIALE' ;
        $response = $this->Effectif->setRAISONSOCIALE($value);
        self::assertInstanceOf(Customers::class, $response);
        self::assertEquals($value, $this->Effectif->getRAISONSOCIALE());

    }


    public function  testGetE():void
    {
        $value = 'test EffecId ' ;
        $response = $this->Effectif->setEffecId($value);
        self::assertInstanceOf(Customers::class, $response);
        self::assertInstanceOf(Admin::class, $this->Effectif->getEffecId());

    }

    public function  testGetNC():void
    {
        $value = 'test NOM_CONTACT' ;
        $response = $this->Effectif->getNOMCONTACT($value);
        self::assertInstanceOf(Customers::class, $response);
        self::assertEquals($value, $this->Effectif->getNOMCONTACT());

    }

}